## PANDAS SERIES

In [2]:
import numpy as np
import pandas as pd

from numpy.random import randn

In [11]:
labels = ['a','b','c']

data = [1,2,3]

In [12]:
#takes two values data and its index i.e key and value pair type
pd.Series(data,labels)

a    1
b    2
c    3
dtype: int64

In [13]:
## hence we can directly use dictionary as key & value are hte two argument required by a pandas series

dit = {'a':100,'b':200,'c':300}

pd.Series(dit)

a    100
b    200
c    300
dtype: int64

## PANDAS DATFRAME

In [15]:
df = pd.DataFrame(randn(5,3),['a','b','c','d','e'],['f','g','h'])

In [16]:
df

          f         g         h
a  0.502066  0.364941  0.093830
b -0.570708  0.388822  0.932692
c  0.917047  1.696111 -1.093632
d -0.140546  0.821558 -1.074367
e -0.330368  0.707975 -1.478566

In [20]:
df['g']

a    0.364941
b    0.388822
c    1.696111
d    0.821558
e    0.707975
Name: g, dtype: float64

In [22]:
#type of the individual column

type(df['g'])

pandas.core.series.Series

In [23]:
df[['g','h']]

          g         h
a  0.364941  0.093830
b  0.388822  0.932692
c  1.696111 -1.093632
d  0.821558 -1.074367
e  0.707975 -1.478566

In [26]:
##to add a new column

df['new_column'] = df['g'] - df['h'] 
df

          f         g         h  new_column
a  0.502066  0.364941  0.093830    0.271111
b -0.570708  0.388822  0.932692   -0.543871
c  0.917047  1.696111 -1.093632    2.789744
d -0.140546  0.821558 -1.074367    1.895925
e -0.330368  0.707975 -1.478566    2.186541

In [28]:
## to access a column from the data-frame

df['g']

a    0.364941
b    0.388822
c    1.696111
d    0.821558
e    0.707975
Name: g, dtype: float64

In [29]:
## to access a row from the data-frame using row name

df.loc['b']

f            -0.570708
g             0.388822
h             0.932692
new_column   -0.543871
Name: b, dtype: float64

In [31]:
## to access a row from the data-frame using index
df.iloc[1]

f            -0.570708
g             0.388822
h             0.932692
new_column   -0.543871
Name: b, dtype: float64

In [39]:
#fetching a value from dataframe laying at intersection of sp.row and sp.column

df.loc[['a','b'],['f','g']]

          f         g
a  0.502066  0.364941
b -0.570708  0.388822

## conditionals (>,<,|,&)

In [15]:
pdf = pd.DataFrame(randn(5,3),['a','b','c','d','e'],['f','g','h'])
pdf

          f         g         h
a  1.074011 -0.788516 -1.252429
b  1.245312 -0.761894 -0.798253
c -0.793506 -1.866436  0.996024
d  1.782053 -0.096076  0.285673
e  0.690030  1.484076 -0.454968

In [16]:
val_1 = pdf['g']>0

In [17]:
pdf[val_1]

         f         g         h
e  0.69003  1.484076 -0.454968

In [18]:
val_2 = (pdf['g']>0) & (pdf['h']<0)  

pdf[val_2]

         f         g         h
e  0.69003  1.484076 -0.454968

In [19]:
val_3 = (pdf['g']>0) | (pdf['h']>0)  

pdf[val_3]

          f         g         h
c -0.793506 -1.866436  0.996024
d  1.782053 -0.096076  0.285673
e  0.690030  1.484076 -0.454968

## resetting & setting index

In [20]:
#adding another column to the dataframe
states = 'CA','NJ','NY','WY','CO'.split() # output is list basically
pdf['States'] = states

In [21]:
pdf

          f         g         h States
a  1.074011 -0.788516 -1.252429     CA
b  1.245312 -0.761894 -0.798253     NJ
c -0.793506 -1.866436  0.996024     NY
d  1.782053 -0.096076  0.285673     WY
e  0.690030  1.484076 -0.454968   [CO]

In [22]:
#reset index i.e index turns out to be first column
reset_idx = pdf.reset_index()
reset_idx

  index         f         g         h States
0     a  1.074011 -0.788516 -1.252429     CA
1     b  1.245312 -0.761894 -0.798253     NJ
2     c -0.793506 -1.866436  0.996024     NY
3     d  1.782053 -0.096076  0.285673     WY
4     e  0.690030  1.484076 -0.454968   [CO]

In [24]:
# set index i.e make any column ofyour choice as index
set_idx = reset_idx.set_index('States')
set_idx

       index         f         g         h
States
CA         a  1.074011 -0.788516 -1.252429
NJ         b  1.245312 -0.761894 -0.798253
NY         c -0.793506 -1.866436  0.996024
WY         d  1.782053 -0.096076  0.285673
[CO]       e  0.690030  1.484076 -0.454968

## Handling Missing Data

In [26]:
dic = {'A':[1,2,np.nan],'B':[3,np.nan,np.nan],'C':[1,3,4]}

DF = pd.DataFrame(dic)
DF

     A    B  C
0  1.0  3.0  1
1  2.0  NaN  3
2  NaN  NaN  4

In [27]:
## droping column having null values

DF_dropcol = DF.dropna(axis=1)
DF_dropcol

   C
0  1
1  3
2  4

In [28]:
## droping rows having null values

DF_droprow = DF.dropna(axis=0)
DF_droprow

     A    B  C
0  1.0  3.0  1

In [29]:
# droping rows having more than 1 null values (same applies to column by making axis=1)

DF_droprow_thresh = DF.dropna(axis=0,thresh=2)
DF_droprow_thresh

     A    B  C
0  1.0  3.0  1
1  2.0  NaN  3

In [32]:
## filling up null values with a default value

DF_default = DF.fillna(value=0)
DF_default

     A    B  C
0  1.0  3.0  1
1  2.0  0.0  3
2  0.0  0.0  4

In [33]:
## filling up formulated values in place of null values

DF_custom_value = DF.fillna(DF['A'].mean()) 
DF_custom_value

     A    B  C
0  1.0  3.0  1
1  2.0  1.5  3
2  1.5  1.5  4

## GROUPBY

In [39]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Sales':[200,120,340,124,243,350]}

Df = pd.DataFrame(data)
Df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [40]:
#find out common  value on multiple rows for a given column(Company in our case) and group them 
company = Df.groupby('Company')
company

In [38]:
##mean of avail col

company.mean('Sales')

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [41]:
#summing up values in a group for column ('Sales')
company.sum('Sales')

         Sales
Company
FB         593
GOOG       320
MSFT       464

In [42]:
#to locate a specific cell 

company.sum('Sales').loc['GOOG']

Sales    320
Name: GOOG, dtype: int64

In [44]:
#min sales
company.min('Sales')

         Sales
Company
FB         243
GOOG       120
MSFT       124

In [46]:
company.max('Sales')

         Sales
Company
FB         350
GOOG       200
MSFT       340